### ISSUE TITLE
Stand-alone JS file?

### ISSUE THREAD

**Issue by andrea-s** [astoilkov/main-thread-scheduling#13]
Since this is a client side library, is it possible to publish a single .js file which exposes this functionality and allows for general purpose importing, without having to build a Node.js project for it?

**Comment by astoilkov** [comment]
Hey, hi. I'm not too familiar with such an approach. Can I ask a few questions to get a better understanding?
- What's your use case? What will you use this for?
- Have you seen this approach somewhere else?
- Does the current multi-file approach prevent you from doing something?

Thanks!

**Comment by andrea-s** [comment]
Hi Antonio, thank for the quick response.

The main idea is that there are many websites that don't use Node.js at all, I am a little unsure of how I could import this library in a project that is not a Node.js app based on your instructions.

In general many libraries (picking a popular example - Highcharts) can be installed by referencing them in a <script> tag in the web page, e.g.:

![image](https://github.com/astoilkov/main-thread-scheduling/assets/9706626/780f103d-62b5-4a59-8349-c358b965f1be)

I hope it's clearer now, let me know!

**Comment by astoilkov** [comment]
Multiple services can do this automatically. The most popular ones that I know of are https://www.unpkg.com/ and https://www.jsdelivr.com/.  Example: https://unpkg.com/main-thread-scheduling@13.0.0/index.js.

Will that work for you?

**Comment by astoilkov** [comment]
I'm closing this. If you have any other questions or feedback, feel free to comment and I will reopen.
