### ISSUE TITLE
Any GC concerns when using async/await

### ISSUE THREAD

**Issue by ScriptedAlchemy** [astoilkov/main-thread-scheduling#2]
If I use a .then() chain, I believe the browser is able to GC better compared to async await which I believe prevents automated GC

Have you come across this scenario before?

**Comment by astoilkov** [comment]
I'm closing this issue as I'm not sure if GC is better when using `.then()` instead of `await`. However, if somebody adds to the conversation I will open it, so we can discuss it further.
