### ISSUE TITLE
Support for postTask scheduling?

### ISSUE THREAD

**Issue by ScriptedAlchemy** [astoilkov/main-thread-scheduling#5]
Hey no came across this article and though this would be a brilliant addition to your work. 

Have any opinion on if or how this could fit into your project? 

https://medium.com/airbnb-engineering/building-a-faster-web-experience-with-the-posttask-scheduler-276b83454e91

**Comment by astoilkov** [comment]
I've mentioned the scheduling API at the end of the [in-depth document](https://github.com/astoilkov/main-thread-scheduling/blob/master/docs/in-depth-overview.md). The `postTask` scheduling is the future and when widely available I will adopt it and replace the current logic. The benefit of my approach (I think) is that it's super simple to use while `postTask` requires a little more effort and code restructuring.

**Comment by astoilkov** [comment]
I've updated the readme to include more information about the `navigator.scheduling` API that's coming in the future. I hope that helps people.

I am closing this issue. Thanks for the idea.
